# Generated by Django 3.2.5 on 2021-12-25 01:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('voltage', models.IntegerField()),
                ('substation_start', models.CharField(max_length=255)),
                ('substation_end', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='SpanField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_end', to='plgis.tower')),
                ('tower_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_start', to='plgis.tower')),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.spanfield')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.tower')),
            ],
        ),
        migrations.CreateModel(
            name='KVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.macro')),
                ('props', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plgis.dictionary')),
            ],
        ),
    ]
