# Generated by Django 3.2.5 on 2022-01-03 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plgis', '0002_auto_20220103_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='date_added',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
